### ISSUE TITLE
Conflicting styles with summery page

### ISSUE THREAD

**Issue by Jam52** [Jam52/the-edward#17]
Some css has been added to global elements (p, h1) please see pics below.

Suggestion:
remove global scoped css and add to specific class?

![header](https://user-images.githubusercontent.com/27687165/100248250-442dde80-2f09-11eb-9991-5fb5e4d7cd29.JPG)

![paragraph](https://user-images.githubusercontent.com/27687165/100248295-514acd80-2f09-11eb-89cc-1f10d70c0bfe.JPG)

**Comment by ghost** [comment]
Changed CSS selectors from element to class.
